
source 'https://github.com/CocoaPods/Specs.git'

target "Demo" do
	pod "AZConstraintsRegister", :path => "../"
end

target "DemoTests" do
	pod "AZConstraintsRegister", :path => "../AZConstraintsRegister.podspec"
  pod 'Specta',      '~> 0.2.1'
  pod 'Expecta',     '~> 0.2.3'
end
